apiVersion: mesh-access.example.com/v1alpha1
kind: AgentMeshEgress
metadata:
  name: agent
spec:
  serviceAccount: agent-client
  inCluster:
  - host: orders
    port: 8080
    protocol: HTTP
  outCluster:
  - host: orders-agent-mesh.remote.example.com
    port: 443
    protocol: MTLS
  - host: api.example.com
    port: 443
    protocol: HTTPS
---
apiVersion: mesh-access.example.com/v1alpha1
kind: AgentMeshExpose
metadata:
  name: orders
spec:
  serviceAccount: orders
  service: orders
  port: 8080
  host: orders-agent-mesh.company.example.com
  gatewaySelector:
    istio: aspe-ingressgateway
  allow:
  - remote-mesh/ns/example/sa/agent-client
