apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  meshConfig:
    trustDomain: cluster-b-mesh
  values:
    global:
      meshID: mesh-access-compat
      multiCluster:
        clusterName: mesh-access134-b
      network: network-b
